### ISSUE TITLE
Getting error on production build

### ISSUE THREAD

**Issue by dyu** [thgh/vuejs-templates-rollup#1]
`Uncaught ReferenceError: production is not defined`

To reproduce:

```
npm run build
npm run serve
# visit localhost:8080
```

I don't get the error with `npm run dev`

**Comment by dyu** [comment]
Vue version was 2.0.0-rc.6

**Comment by dyu** [comment]
Its an uglifyjs issue.  Tried a specific version of closure-compiler and it worked fine.

**Comment by thgh** [comment]
Thanks for trying this tempate!

It's an uglifyjs issue indeed, but was able to avoid it in rollup-plugin-vue2. It's related to replacing `process.env.__NODE_ENV__` to something that works in the browser. Updating the vue2 plugin should get it working now.

**Comment by anthonygore** [comment]
Can you explain how to solve this? I'm getting the same error on Vue 2.0.2

**Comment by anthonygore** [comment]
Actually I solved it in my case by changing webpack config from:

```
new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: 'production'
      }
    }),
```

to:

```
new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
```

**Comment by lucnap** [comment]
this reduced my vendor bundle size from 1.3MB to 800kb!!!!

**Comment by melkishengue** [comment]
Hey @anthonygore, I am facing the same problem with vue and webpack 2. I tried your solution, it works, but I am wondering if this will not have any side effect for webpack or other webpack plugins that expect the string `production` and not the `"production"`. Any idea about that ?
